services:
  think-forge:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinkforge:latest
    container_name: think-forge
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306  # 容器内部端口保持 3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=930201
      - MYSQL_DATABASE=thinkforge
    volumes:
      - ./server/manifest/config/config.yaml:/app/manifest/config/config.yaml
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.routing.allocation.disk.watermark.low=1gb"
      - "cluster.routing.allocation.disk.watermark.high=1gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=1gb"
    ports:
      - "9200:9200"
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=930201
      - MYSQL_DATABASE=thinkforge
      - MYSQL_ROOT_HOST=%
      - MYSQL_CHARSET=utf8mb4
    ports:
      - "3309:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p930201" ]
      interval: 10s
      timeout: 5s
      retries: 10